export const CHANGE_TOP_BANNER = 'recommend/changeTopBanner'
export const CHANGE_HOT_RECOMMEND = 'recommend/changeHotRecommend'
export const CHANGE_NEW_ALBUMS = 'recommend/changeNewAlbums'
export const CHANGE_NEW_LIST = 'recommend/changeNewList'
export const CHANGE_UP_LIST = 'recommend/changeUpList'
export const CHANGE_ORIGIN_LIST = 'recommend/changeOriginList'
export const CHANGE_TOP_ARTIST = 'recommend/changeTopArtist'
export const CHANGE_HOT_DJ = 'recommend/changeHotDj'
