export const CHANGE_SEARCH_SONGS = '/search/changeSearchSongs'
export const CHANGE_SEARCH_SONGSTOTAL = '/search/changeSearchSongsTotal'
export const CHANGE_SEARCH_ARTISTS = '/search/changeSearchArtists'
export const CHANGE_SEARCH_ARTISTSTOTAL = '/search/changeSearchArtistsTotal'
export const CHANGE_SEARCH_ALBUMS= '/search/changeSearchAlbums'
export const CHANGE_SEARCH_ALBUMSTOTAL = '/search/changeSearchAlbumsTotal'
export const CHANGE_SEARCH_VIDEOS= '/search/changeSearchVideos'
export const CHANGE_SEARCH_VIDEOSTOTAL = '/search/changeSearchVideosTotal'
