export const CHANGE_MV_DETAIL = 'mv/chagneMvDetail'
export const CHANGE_MV_URL = 'mv/chagneMvURL'
export const CHANGE_VIDEO_DETAIL = 'mv/chagneVideoDetail'
export const CHANGE_VIDEO_URL = 'mv/chagneVideoURL'
export const CHANGE_RELATED_MVS = 'mv/changerelatedMvs'
