export const CHANGE_SONG_COMMENT = 'comment/changeSongComment'
export const CHANGE_SONG_HOT_COMMENT = 'comment/changeSongHotComment'
export const CHANGE_SONG_COMMENT_TOTAL = 'comment/changeSongCommentTotal'
export const CHANGE_MV_COMMENT = 'comment/changeMvComment'
export const CHANGE_MV_HOT_COMMENT = 'comment/changeMvHotComment'
export const CHANGE_MV_COMMENT_TOTAL = 'comment/changeMvCommentTotal'
export const CHANGE_PLAYLIST_COMMENT = 'comment/changePlayListComment'
export const CHANGE_PLAYLIST_HOT_COMMENT = 'comment/changePlayListHotComment'
export const CHANGE_PLAYLIST_COMMENT_TOTAL =
  'comment/changePlayListCommentTotal'
export const CHANGE_ALBUM_COMMENT = 'comment/changAlbumComment'
export const CHANGE_ALBUM_HOT_COMMENT = 'comment/changeAlbumHotComment'
export const CHANGE_ALBUM_COMMENT_TOTAL = 'comment/changeAlbumCommentTotal'
