export const CHANGE_SONG_COMMENT = 'comment/changeSongComment'
export const CHANGE_SONG_HOT_COMMENT = 'comment/changeSongHotComment'
export const CHANGE_SONG_COMMENT_TOTAL = 'comment/changeSongCommentTotal'
export const CHANGE_MV_COMMENT = 'comment/changeMvComment'
export const CHANGE_MV_HOT_COMMENT = 'comment/changeMvHotComment'
export const CHANGE_MV_COMMENT_TOTAL = 'comment/changeMvCommentTotal'
